# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: split-bill-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=8967451230
      - DB_NAME=splitbill
      - IP_ADDRESS=0.0.0.0
      - API_PORT=8080
    depends_on:
      - postgres
    networks:
      - split-bill-network
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: split-bill-postgres
    environment:
      - POSTGRES_DB=splitbill
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8967451230
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - split-bill-network
    restart: unless-stopped

  # Опционально: pgAdmin для управления БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: split-bill-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - split-bill-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  split-bill-network:
    driver: bridge